version: '3'
services:
  web:
    build: .
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - HOST=${HOST}
      - USER_HOST=${USER_HOST}
      - PASSWORD_HOST=${PASSWORD_HOST}
      - DB_HOST=${DB_HOST}
    ports:
      - "5007:5000"
